import matplotlib.pyplot as plt
import seaborn as sns
print("--DATASETS GIVEN IN THE SEABORN--\n",sns.get_dataset_names())
iris=sns.load_dataset("iris")
print("-----IRIS DATASET HEAD-----\n",iris.head())
anagrams=sns.load_dataset("anagrams")
carcrashes=sns.load_dataset("car_crashes")
print("-----CAR CRASHES DATASET-----------\n",carcrashes.head())
print("-----ANAGRAMS DATASET HEAD----\n",anagrams.head())
print("---IRIS DATASET----\n",iris.count())
print("-----ANAGRAMS DATASET----\n",anagrams.count())
print("A FIGURE LEVEL FUNCTION CONTROLS THE FIGURE CATPLOT,RELPLOT")
sns.catplot(x="species",y="petal_length",kind="box",data=iris)
plt.show()
sns.catplot(x="species",y="petal_length",kind="swarm",data=iris)
plt.show()
sns.catplot(x="num2",y="num3",kind="box",data=anagrams)
plt.show()
sns.catplot(x="num2",y="num3",kind="swarm",data=anagrams)
plt.show()
sns.catplot(x="total",y="speeding",kind="box",data=carcrashes)
plt.show()
